### ISSUE TITLE
Admin links not showing (SugarCRM 6.5.15)

### ISSUE THREAD

**Issue by danielneal** [jjwdesign/JJWDesign-Google-Maps#5]
I'm running SugarCRM 6.5.15 on a rackspace server, and just installed the most recent version of your excellent google maps plugin. 

Unfortunately the admin links do not appear in the admin page. 

I'm very new to SugarCRM so at a loss how to debug it.
I noticed you had a couple of commit messages relating to admin links recently, so I wondered if this was a known issue/something you're working on?

Strangely, the links seem to work on my local machine (running SugarCRM 6.5.14). 
Will try upgrading my local instance to 6.5.15 to see if that makes them disappear. 

Anyways, hope you can help - the module (which I've got running locally) is a fantastic piece of work!

**Comment by Danisan** [comment]
The best practice with this is the following:
for SugarCRM:

chown -R <apachegroup>:<apacheuser> <sugarpath>
find <sugarpath -type d -exec chmod 755 {} \;
find <sugarpath -type f -exec chmod 644 {} \;

You should also check in config.php the following values:

array (
    'dir_mode' => 1517,
    'file_mode' => 420,
    'user' => '<apacheuser>',
    'group' => '<apachegroup>',
  ),

where <apacheuser> and <apachegroup> should be the group and user under which apache is running. (in ubuntu for example, www-data for both). and <..path> is the path in the file system where crm is running (for example /var/www/crm, or /opt/sugar/public_html).

In SuiteCRM is easier:
chown -R <apachegroup>:<apacheuser> <suitecrmpath>
chmod -R 755 <suitecrmpath>
cd <suitecrmpath>
chmod -R 775 cache custom modules themes data upload config_override.php 

and in config:

array (
    'dir_mode' => 1517,
    'file_mode' => 493,
    'user' => '<apacheuser>',
    'group' => '<apachegroup>',
),
